# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0e51960142587f85140f383069dc1f8c1e9a598cf8b6e3239140b922e9ffb4e5429be730da21895b6798b757daf4585157a3f893f94bb80b0c0e6173aab446c6

test:
  secret_key_base: 12d69b32e493c8040aaa3c427f20942c2e4f6c3ff4e03c9be3a9a8e1211b68fd1b292e984cf4f771529e073a0738612dac4c907ac5804e09c34a311df57f1d01

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
